language: ruby
rvm:
  - 1.9.3
  - ruby-head
  - rbx-19mode

bundler_args: "--without development production assets"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode

script:
  - "RAILS_ENV=test bundle exec rake db:test:prepare"
  - "bundle exec rspec"
  - "bundle exec cucumber"
